const throwError = async ({message}) => {
    throw new Error(message)
}

export default throwError;